[[language]]
auto-format = true
language-servers = ["nixd"]
name = "nix"

[language.formatter]
command = "alejandra"

[[language]]
auto-format = true
name = "lua"

[[language]]
auto-format = true
language-servers = ["marksman", "markdown-oxide", "harper-ls", "mpls"]
name = "markdown"

[language.formatter]
args = ["--parser", "--markdown", "--prose-wrap", "never"]
command = "prettier"
